server:
  port: 8761
  servlet:
    context-path: /demo

spring:
  application:
    name: redission-redis
  redis:
    database: 0 #Redis数据库索引（默认为0 redis有16个库）
    host: localhost #地址
    port: 6379 # Redis服务器连接端口（端口安装默认的）
    timeout: 10000ms  # 连接超时时间（记得添加单位，Duration）
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
