application:
  name: prod @artifactId@
  version: prod @version@
developer-property:
  name: prod zhangwei
  website: prod https//localhost:${server.port}
  qq: prod ${random.int(10)}
  phone-number: prod ${random.int(11)}