server:
  port: 8761
  servlet:
    context-path: /demo
spring:
  swagger:
    enable: true
    title: spring-boot-swagger-beauty
    # swagger扫描的基础包，默认：全扫描
    base-package: com.zw.controller
    # 需要处理的基础URL规则，默认：/**
    base-path: /user/**
    # 需要排除的URL规则，默认：空
    # exclude-path:
    description: spring boot swagger beauty demo演示
    version: 1.0.0-SNAPSHOT
    contact:
      name: WeiZhang
    security:
      # 是否启用 swagger 登录验证
      filter-plugin: true
      username: weizhang
      password: 123456
    global-response-messages:
      GET[0]:
        code: 400
        message: Bad Request，一般为请求参数不对
      GET[1]:
        code: 404
        message: NOT FOUND，一般为请求路径不对
      GET[2]:
        code: 500
        message: ERROR，一般为程序内部错误
      POST[0]:
        code: 400
        message: Bad Request，一般为请求参数不对
      POST[1]:
        code: 404
        message: NOT FOUND，一般为请求路径不对
      POST[2]:
        code: 500
        message: ERROR，一般为程序内部错误