server:
  port: 8761
  servlet:
    context-path: /demo
spring:
  redis:
    database: 0 #Redis数据库索引（默认为0 redis有16个库）
    host: localhost #地址
    port: 6379 # Redis服务器连接端口（端口安装默认的）
    #password:Redis服务器连接密码（默认为空）
    timeout: 10000ms  # 连接超时时间（记得添加单位，Duration）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
    cache:
        # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
        type: redis
  jackson:
        # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
        property-naming-strategy: SNAKE_CASE
        # 全局设置@JsonFormat的格式pattern
        date-format: yyyy-MM-dd HH:mm:ss
        # 当地时区
        locale: zh
        # 设置全局时区
        time-zone: GMT+8
        # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
        default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
        # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
          FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
        # 枚举类DeserializationFeature中的枚举属性为key，值为boolean设置jackson反序列化特性,具体key请看DeserializationFeature源码
        deserialization:
          # 常用,json中含pojo不存在属性时是否失败报错,默认true
          FAIL_ON_UNKNOWN_PROPERTIES: false
        # 枚举类MapperFeature中的枚举属性为key，值为boolean设置jackson ObjectMapper特性
        # ObjectMapper在jackson中负责json的读写、json与pojo的互转、json tree的互转,具体特性请看MapperFeature,常规默认即可
        mapper:
          # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性
          USE_GETTERS_AS_SETTERS: true #默认false
        # 枚举类JsonParser.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonParser特性
        # JsonParser在jackson中负责json内容的读取,具体特性请看JsonParser.Feature，一般无需设置默认即可
        parser:
          ALLOW_SINGLE_QUOTES: true # 是否允许出现单引号,默认false
        # 枚举类JsonGenerator.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonGenerator特性，一般无需设置默认即可
        # JsonGenerator在jackson中负责编写json内容,具体特性请看JsonGenerator.Feature
logging:
  level:
    com.zw: debug