server:
  port: 8761
#同SecurityConfig 设置
#spring:
#  security:
#    user:
#      name: zhangwei
#      password: 123456
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnjdbc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456